"""create core identity and tenancy tables

Revision ID: 5051e31d1600
Revises:
Create Date: 2026-09-14 13:50:24.150090
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "5051e31d1600"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "core_apps",
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_core_apps")),
        sa.UniqueConstraint("code", name=op.f("uq_core_apps_code")),
    )
    op.create_table(
        "core_organizations",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_core_organizations")),
        sa.UniqueConstraint("slug", name=op.f("uq_core_organizations_slug")),
    )
    op.create_table(
        "core_permissions",
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_core_permissions")),
        sa.UniqueConstraint("code", name=op.f("uq_core_permissions_code")),
    )
    op.create_table(
        "core_users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=512), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("mfa_enabled", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_core_users")),
        sa.UniqueConstraint("email", name=op.f("uq_core_users_email")),
    )
    op.create_table(
        "core_audit_events",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("resource_type", sa.String(length=100), nullable=False),
        sa.Column("resource_id", sa.String(length=100), nullable=True),
        sa.Column("result", sa.String(length=20), nullable=False),
        sa.Column("safe_metadata", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["core_users.id"],
            name=op.f("fk_core_audit_events_actor_id_core_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["core_organizations.id"],
            name=op.f("fk_core_audit_events_organization_id_core_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_core_audit_events")),
    )
    op.create_index(
        "ix_core_audit_events_org_created",
        "core_audit_events",
        ["organization_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "core_auth_sessions",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["core_users.id"],
            name=op.f("fk_core_auth_sessions_user_id_core_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_core_auth_sessions")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_core_auth_sessions_token_hash")),
    )
    op.create_index(
        op.f("ix_core_auth_sessions_user_id"), "core_auth_sessions", ["user_id"], unique=False
    )
    op.create_table(
        "core_feature_flags",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["core_organizations.id"],
            name=op.f("fk_core_feature_flags_organization_id_core_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_core_feature_flags")),
        sa.UniqueConstraint(
            "organization_id", "key", name=op.f("uq_core_feature_flags_organization_id")
        ),
    )
    op.create_index(
        op.f("ix_core_feature_flags_organization_id"),
        "core_feature_flags",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "core_integrations",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("safe_metadata", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["core_organizations.id"],
            name=op.f("fk_core_integrations_organization_id_core_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_core_integrations")),
    )
    op.create_index(
        op.f("ix_core_integrations_organization_id"),
        "core_integrations",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "core_notifications",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["core_organizations.id"],
            name=op.f("fk_core_notifications_organization_id_core_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["core_users.id"],
            name=op.f("fk_core_notifications_user_id_core_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_core_notifications")),
    )
    op.create_index(
        op.f("ix_core_notifications_organization_id"),
        "core_notifications",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "core_organization_apps",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("app_id", sa.Uuid(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["app_id"],
            ["core_apps.id"],
            name=op.f("fk_core_organization_apps_app_id_core_apps"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["core_organizations.id"],
            name=op.f("fk_core_organization_apps_organization_id_core_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_core_organization_apps")),
        sa.UniqueConstraint(
            "organization_id", "app_id", name=op.f("uq_core_organization_apps_organization_id")
        ),
    )
    op.create_index(
        op.f("ix_core_organization_apps_organization_id"),
        "core_organization_apps",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "core_roles",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["core_organizations.id"],
            name=op.f("fk_core_roles_organization_id_core_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_core_roles")),
        sa.UniqueConstraint("organization_id", "id", name="uq_core_roles_org_id"),
        sa.UniqueConstraint("organization_id", "name", name="uq_core_roles_org_name"),
    )
    op.create_index(
        op.f("ix_core_roles_organization_id"), "core_roles", ["organization_id"], unique=False
    )
    op.create_table(
        "core_subscriptions",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["core_organizations.id"],
            name=op.f("fk_core_subscriptions_organization_id_core_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_core_subscriptions")),
    )
    op.create_index(
        op.f("ix_core_subscriptions_organization_id"),
        "core_subscriptions",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "core_memberships",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "role_id"],
            ["core_roles.organization_id", "core_roles.id"],
            name=op.f("fk_core_memberships_organization_id_core_roles"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["core_organizations.id"],
            name=op.f("fk_core_memberships_organization_id_core_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["core_users.id"],
            name=op.f("fk_core_memberships_user_id_core_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_core_memberships")),
        sa.UniqueConstraint(
            "organization_id", "user_id", name=op.f("uq_core_memberships_organization_id")
        ),
    )
    op.create_index(
        op.f("ix_core_memberships_organization_id"),
        "core_memberships",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_core_memberships_user_id"), "core_memberships", ["user_id"], unique=False
    )
    op.create_table(
        "core_role_permissions",
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("permission_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["core_permissions.id"],
            name=op.f("fk_core_role_permissions_permission_id_core_permissions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["core_roles.id"],
            name=op.f("fk_core_role_permissions_role_id_core_roles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("role_id", "permission_id", name=op.f("pk_core_role_permissions")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("core_role_permissions")
    op.drop_index(op.f("ix_core_memberships_user_id"), table_name="core_memberships")
    op.drop_index(op.f("ix_core_memberships_organization_id"), table_name="core_memberships")
    op.drop_table("core_memberships")
    op.drop_index(op.f("ix_core_subscriptions_organization_id"), table_name="core_subscriptions")
    op.drop_table("core_subscriptions")
    op.drop_index(op.f("ix_core_roles_organization_id"), table_name="core_roles")
    op.drop_table("core_roles")
    op.drop_index(
        op.f("ix_core_organization_apps_organization_id"), table_name="core_organization_apps"
    )
    op.drop_table("core_organization_apps")
    op.drop_index(op.f("ix_core_notifications_organization_id"), table_name="core_notifications")
    op.drop_table("core_notifications")
    op.drop_index(op.f("ix_core_integrations_organization_id"), table_name="core_integrations")
    op.drop_table("core_integrations")
    op.drop_index(op.f("ix_core_feature_flags_organization_id"), table_name="core_feature_flags")
    op.drop_table("core_feature_flags")
    op.drop_index(op.f("ix_core_auth_sessions_user_id"), table_name="core_auth_sessions")
    op.drop_table("core_auth_sessions")
    op.drop_index("ix_core_audit_events_org_created", table_name="core_audit_events")
    op.drop_table("core_audit_events")
    op.drop_table("core_users")
    op.drop_table("core_permissions")
    op.drop_table("core_organizations")
    op.drop_table("core_apps")
    # ### end Alembic commands ###
