"""add password recovery tokens

Revision ID: c270fea90fb2
Revises: 5051e31d1600
Create Date: 2026-09-14 14:37:40.415586
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "c270fea90fb2"
down_revision: str | None = "5051e31d1600"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "core_password_reset_tokens",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["core_users.id"],
            name=op.f("fk_core_password_reset_tokens_user_id_core_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_core_password_reset_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_core_password_reset_tokens_token_hash")),
    )
    op.create_index(
        op.f("ix_core_password_reset_tokens_user_id"),
        "core_password_reset_tokens",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_core_password_reset_tokens_user_id"), table_name="core_password_reset_tokens"
    )
    op.drop_table("core_password_reset_tokens")
    # ### end Alembic commands ###
